CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250926215840_AddAuthentication', '9.0.9');

CREATE TABLE "ElementTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text,
    CONSTRAINT "PK_ElementTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "Elements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ElementTypeId" integer,
    CONSTRAINT "PK_Elements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Elements_ElementTypes_ElementTypeId" FOREIGN KEY ("ElementTypeId") REFERENCES "ElementTypes" ("Id")
);

CREATE INDEX "IX_Elements_ElementTypeId" ON "Elements" ("ElementTypeId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250927182221_AddElement', '9.0.9');

CREATE TABLE "Projects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text,
    "CreationDate" timestamp with time zone NOT NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Projects_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Projects_UserId" ON "Projects" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250929051222_AddProject', '9.0.9');

ALTER TABLE "Elements" ADD "ProjectId" integer NOT NULL DEFAULT 0;

CREATE INDEX "IX_Elements_ProjectId" ON "Elements" ("ProjectId");

ALTER TABLE "Elements" ADD CONSTRAINT "FK_Elements_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250929125929_AddProjectToElement', '9.0.9');

CREATE TABLE "RequirementTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Description" text,
    CONSTRAINT "PK_RequirementTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "Versions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "ElementUrl" text NOT NULL,
    "UploadDate" timestamp with time zone NOT NULL,
    "State" text NOT NULL,
    "ToolUrl" text,
    "VersionCode" text NOT NULL,
    "ElementId" integer NOT NULL,
    "UserId" text NOT NULL,
    "RequirementTypeId" integer NOT NULL,
    "ParentVersionId" integer,
    CONSTRAINT "PK_Versions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Versions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Versions_Elements_ElementId" FOREIGN KEY ("ElementId") REFERENCES "Elements" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Versions_RequirementTypes_RequirementTypeId" FOREIGN KEY ("RequirementTypeId") REFERENCES "RequirementTypes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Versions_Versions_ParentVersionId" FOREIGN KEY ("ParentVersionId") REFERENCES "Versions" ("Id")
);

CREATE INDEX "IX_Versions_ElementId" ON "Versions" ("ElementId");

CREATE INDEX "IX_Versions_ParentVersionId" ON "Versions" ("ParentVersionId");

CREATE INDEX "IX_Versions_RequirementTypeId" ON "Versions" ("RequirementTypeId");

CREATE INDEX "IX_Versions_UserId" ON "Versions" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250930061810_AddVersion', '9.0.9');

ALTER TABLE "Versions" ADD "Phase" integer NOT NULL DEFAULT 1;

ALTER TABLE "Versions" ADD iteration integer NOT NULL DEFAULT 1;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251002165725_AddLifeCycleSoftwareToVersion', '9.0.9');

ALTER TABLE "Elements" ADD "ExternaCodeElement" text;

ALTER TABLE "Elements" ADD "ExternalUrlElement" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251005115945_AddIntegrationGithub', '9.0.9');

CREATE TABLE "ChangeRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClasificationType" integer NOT NULL,
    "Description" text,
    "Priority" integer NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Remarks" text,
    "Action" integer,
    "ElementId" integer NOT NULL,
    CONSTRAINT "PK_ChangeRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChangeRequests_Elements_ElementId" FOREIGN KEY ("ElementId") REFERENCES "Elements" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ChangeRequests_ElementId" ON "ChangeRequests" ("ElementId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251006023119_AddChangeRequest', '9.0.9');

ALTER TABLE "Versions" ADD "ChangeRequestId" integer NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX "IX_Versions_ChangeRequestId" ON "Versions" ("ChangeRequestId");

ALTER TABLE "Versions" ADD CONSTRAINT "FK_Versions_ChangeRequests_ChangeRequestId" FOREIGN KEY ("ChangeRequestId") REFERENCES "ChangeRequests" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251006041138_AddChangeRequestToVersion', '9.0.9');

ALTER TABLE "ChangeRequests" ADD "Code" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251006112022_AddCodeToChangeRequest', '9.0.9');

COMMIT;

